# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 234obi Autodeploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Git Pull on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/peterobi/23ForObi/frontend
            git fetch --all 
            git reset --hard origin/main
            git stash
            git pull
            npm install
            cd ../
            source env/bin/activate
            python -m pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt
            pm2 restart peterobi
